### PR TITLE
Use new stable repo URL for `stable/` prefix

### LINKED ISSUE #1446: Can't helm deploy postgresql from django example
**What happened?**  

Trying out some of the bits from https://devspace.cloud/blog/2019/10/18/deploy-django-to-kubernetes on https://github.com/loft-sh/devspace-quickstart-python

Adding 

```
- name: database
  helm:
    chart:
      name: stable/postgresql
      version: "6.5.9"
    values:
      postgresqlDatabase: "db_mysite"
      postgresqlUsername: "db_user"
      postgresqlPassword: ${DB_PASSWORD}
```
to my `devspace.yaml`

When I try to do `devspace dev` I get : 

```
devspace dev
[info]   Using namespace 'devspace-demo'
[info]   Using kube context 'kind-kind'
[info]   Skipping building image app                                            
                                                                                                                       [info]   Execute 'helm upgrade devspace-quickstart-python /home/arthur/.devspace/component-chart/component-chart-0.7.1.tgz --namespace devspace-demo --values /tmp/432245245 --install --kube-context kind-kind'
                                                                                                                       [info]   Execute 'helm list --namespace devspace-demo --output json --kube-context kind-kind'
                                                                                                                       [done] √ Deployed helm chart (Release revision: 10)
                                                                                                                       [done] √ Successfully deployed devspace-quickstart-python with helm
[info]   Execute 'helm upgrade database postgresql --namespace devspace-demo --values /tmp/993813816 --install --repo https://kubernetes-charts.storage.googleapis.com --repository-config='' --kube-context kind-kind'
[fatal]  error deploying: error deploying database: Unable to deploy helm chart: error during 'helm upgrade database postgresql --namespace devspace-demo --values /tmp/993813816 --install --repo https://kubernetes-charts.storage.googleapis.com --repository-config='' --kube-context kind-kind': Release "database" does not exist. Installing it now.
Error: looks like "https://kubernetes-charts.storage.googleapis.com" is not a valid chart repository or cannot be reached: failed to fetch https://kubernetes-charts.storage.googleapis.com/index.yaml : 403 Forbidden
 => exit status 1
Run `devspace purge -d database` and `devspace deploy` to recreate the chart
```

Running `helm repo update` I don't see any old `googleapis.com` URLs. Am running with helm v3. 

**What did you expect to happen instead?**  

Deployment of postgresql to work. 

**How can we reproduce the bug?** (as minimally and precisely as possible)  

**Local Environment:**  
- DevSpace Version: 5.13.0
- Operating System: linux 
- Deployment method: helm 

**Kubernetes Cluster:**  
- Cloud Provider: kind
- Kubernetes Version: 

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

**Anything else we need to know?**  

/kind bug

### PR DESCRIPTION
**Pull request by nVitius**
**What issue type does this pull request address?** (keep at least one, remove the others)  
/kind bug

**What is this pull request for? Which issues does it resolve?** (use `resolves #<issue_number>` if possible)  
resolves #1446

**Does this pull request has user-facing changes?** (e.g. config changes, new/modified commands, new/modified flags)  
no

**Does this pull request add new dependencies?**  
no

**What else do we need to know?**  
Helm changed the URL for their stable and incubator charts last year. The old URLs were deprecated in November.
https://helm.sh/blog/new-location-stable-incubator-charts/

### CODE REVIEW

**Comment by FabianKramm** [comment]
@nVitius thanks for creating this PR, does that still work, I thought the stable repo does not exist anymore?

**Comment by nVitius** [comment]
@FabianKramm the stable repo has indeed been deprecated. However, all the charts that existed on there are archived under the URL I added. Here is a link to the Github repo where these exist: https://github.com/helm/charts


I've only recently started using devspace and helm. I ran into issues when trying to follow some of the devspace docs that references using `stable/` charts. Installing a chart from this repo will make Helm generate a warning, but they will still work.

Perhaps we want to eventually remove the `stable/` helper in the devspace codebase, but I think this is at least better than what it is currently. The existing code will try to install from a repo that doesn't exist and present the user with an error that might be hard to understand.

**Comment by FabianKramm** [comment]
@nVitius thanks for the explaination. Yes that makes sense, currently it wouldn't work at all, so we can change that!

**Review by FabianKramm — APPROVED** [review]
LGTM

**Pull request merged**
